version: '3.3'

services:
  elasticsearch:
    container_name: es-01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=true
      - bootstrap.memory_lock=false
      - ELASTIC_PASSWORD=password
      - discovery.type=single-node
      # Multi node setup
      # - node.name=es-01
      # - cluster.name=es-docker-cluster
      # - cluster.initial_master_nodes=es-01
      # - discovery.seed_hosts=es-01,es-02
    volumes:
      - data-01:/usr/share/elasticsearch/data
      - ./ELK/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

#  logstash:
#    container_name: logstash
#    image: docker.elastic.co/logstash/logstash:7.14.0
#    ports:
#       - "5044:5044"
#       - "5000:5000/tcp"
#       - "5000:5000/udp"
#    volumes:
#       - ./ELK/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
#       - ./ELK/logstash/pipeline:/usr/share/logstash/pipeline
#    depends_on:
#      - elasticsearch
#    networks:
#      - elastic
 
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./ELK/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  data-01:
    driver: local

networks:
  elastic:
    driver: bridge
